import type { DocumentTemplate } from './templates'

// ---------------------------------------------------------------------------
// PDF generation using @react-pdf/renderer
// ---------------------------------------------------------------------------

export async function generatePDF(
  template: DocumentTemplate,
  content: Record<string, string>
): Promise<Buffer> {
  // Dynamic import to avoid issues with SSR/Edge runtime
  const { pdf, Document, Page, Text, View, StyleSheet } = await import('@react-pdf/renderer')
  const React = await import('react')

  const styles = StyleSheet.create({
    page: { padding: 60, fontFamily: 'Times-Roman', fontSize: 11, lineHeight: 1.6 },
    header: { marginBottom: 24, paddingBottom: 12, borderBottom: '1 solid #cccccc' },
    title: { fontSize: 14, fontWeight: 'bold', textAlign: 'center' },
    subtitle: { fontSize: 9, color: '#888888', textAlign: 'center', marginTop: 4 },
    label: { fontWeight: 'bold', marginTop: 14, fontSize: 9, color: '#555555', textTransform: 'uppercase' },
    value: { marginTop: 2, marginBottom: 4, fontSize: 11 },
    disclaimer: {
      marginTop: 36,
      fontSize: 8,
      color: '#888888',
      borderTop: '1 solid #cccccc',
      paddingTop: 10,
      lineHeight: 1.5,
    },
  })

  const doc = React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: 'A4', style: styles.page },
      React.createElement(
        View,
        null,
        React.createElement(
          View,
          { style: styles.header },
          React.createElement(Text, { style: styles.title }, template.label),
          React.createElement(Text, { style: styles.subtitle }, 'Generated by Petty Lawsuits')
        ),
        ...template.fields.map(field =>
          React.createElement(
            View,
            { key: field.key },
            React.createElement(Text, { style: styles.label }, field.label),
            React.createElement(Text, { style: styles.value }, content[field.key] ?? '')
          )
        ),
        React.createElement(
          Text,
          { style: styles.disclaimer },
          'This document was generated using a template tool. It is not legal advice. You should seek independent legal advice if you are unsure about your rights or obligations.'
        )
      )
    )
  )

  const instance = pdf(doc)
  // toBuffer() returns a ReadableStream in types but a Buffer in Node.js runtime
  const result = await instance.toBuffer() as unknown as Buffer
  return Buffer.isBuffer(result) ? result : Buffer.from(result as unknown as ArrayBuffer)
}

// ---------------------------------------------------------------------------
// Word generation using docx
// ---------------------------------------------------------------------------

export async function generateWord(
  template: DocumentTemplate,
  content: Record<string, string>
): Promise<Buffer> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import('docx')

  const children = [
    new Paragraph({ text: template.label, heading: HeadingLevel.HEADING_1 }),
    new Paragraph({ text: 'Generated by Petty Lawsuits', style: 'aside' }),
    new Paragraph({ text: '' }),
    ...template.fields.flatMap(field => [
      new Paragraph({
        children: [new TextRun({ text: field.label + ':', bold: true, size: 20 })],
        spacing: { before: 240 },
      }),
      new Paragraph({
        children: [new TextRun({ text: content[field.key] ?? '', size: 22 })],
        spacing: { after: 80 },
      }),
    ]),
    new Paragraph({ text: '' }),
    new Paragraph({
      children: [
        new TextRun({
          text: 'This document was generated using a template tool. It is not legal advice. You should seek independent legal advice if you are unsure about your rights or obligations.',
          italics: true,
          size: 16,
          color: '888888',
        }),
      ],
      spacing: { before: 400 },
    }),
  ]

  const doc = new Document({ sections: [{ children }] })
  return await Packer.toBuffer(doc)
}
