export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-20 md:py-24">
      <h1 className="text-4xl md:text-5xl text-center mb-4">Terms of Service</h1>
      <p className="text-center text-[var(--muted)] text-lg mb-4">
        Please read these terms before using Petty Lawsuits.
      </p>

      <div className="mb-12 border border-[var(--accent)] rounded-lg p-5 bg-[var(--card)]">
        <p className="text-sm font-medium text-[var(--accent)] mb-1">DRAFT — Not yet reviewed by a lawyer</p>
        <p className="text-sm text-[var(--muted)] leading-relaxed">
          These Terms of Service are a placeholder. They have not been reviewed or approved by a
          qualified legal professional and should not be relied upon as legally enforceable. We will
          replace this with lawyer-reviewed terms before launch.
        </p>
      </div>

      <div className="space-y-8">

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">1. About this service</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>
              Petty Lawsuits is a document generation tool. We help Australians create formal legal
              documents — including demand letters, complaint notices, and tribunal filings — based on
              information you provide.
            </p>
            <p className="font-medium text-[var(--foreground)]">
              Petty Lawsuits is not a law firm. We do not provide legal advice, legal representation,
              or any form of legal service.
            </p>
            <p>
              The documents we generate are templates informed by your inputs. They are not a
              substitute for professional legal advice. If you are unsure about your legal rights or
              obligations, we strongly recommend seeking independent advice from a qualified Australian
              legal practitioner.
            </p>
          </div>
        </section>

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">2. Who can use this service</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>By using Petty Lawsuits, you confirm that:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>You are at least 18 years of age</li>
              <li>You are located in Australia or your dispute relates to an Australian jurisdiction</li>
              <li>You will use the service for lawful purposes only</li>
              <li>The information you provide is accurate and truthful to the best of your knowledge</li>
            </ul>
          </div>
        </section>

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">3. User responsibilities</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>You are responsible for:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>The accuracy of the information you provide when generating documents</li>
              <li>Reviewing your document before sending or filing it</li>
              <li>Determining whether the document is appropriate for your specific circumstances</li>
              <li>Complying with any tribunal, court, or regulatory requirements that apply to your dispute</li>
              <li>Not using any document generated by this service for fraudulent, harassing, or unlawful purposes</li>
            </ul>
            <p className="mt-3">
              We reserve the right to suspend or terminate access to the service if we reasonably believe a user is engaging in misuse or abuse.
            </p>
          </div>
        </section>

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">4. Payment terms</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>
              Documents are sold on a <strong className="text-[var(--foreground)]">one-time, per-document basis</strong>. There are currently no subscription plans. All prices are in Australian dollars (AUD) and are inclusive of GST where applicable.
            </p>
            <p>
              Payment is processed securely by Stripe. You will be charged at the time you unlock your document. A receipt will be emailed to you.
            </p>
            <p>
              <strong className="text-[var(--foreground)]">Refunds:</strong> If document generation fails after payment, we will issue a full refund. For other issues, contact us and we will work it out on a case-by-case basis. We do not offer refunds for change of mind once a document has been successfully generated and delivered.
            </p>
          </div>
        </section>

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">5. Intellectual property</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>
              The document templates, software, and content on this platform are owned by or licensed to Petty Lawsuits. You may not reproduce, resell, or distribute our templates or software without permission.
            </p>
            <p>
              The specific document generated for your dispute — using your own factual details — is yours to use for the purpose for which it was created.
            </p>
          </div>
        </section>

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">6. Limitation of liability</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>
              To the maximum extent permitted by Australian law, Petty Lawsuits and its operators are not liable for:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Any legal outcome resulting from the use of a document generated by this service</li>
              <li>Errors or inaccuracies in generated documents</li>
              <li>Loss or damage arising from your reliance on this service in place of professional legal advice</li>
              <li>Any indirect, consequential, or incidental loss</li>
            </ul>
            <p className="mt-3">
              Nothing in these terms excludes any guarantee, warranty, or right that cannot be excluded under the Australian Consumer Law.
            </p>
          </div>
        </section>

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">7. Governing law</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>
              These terms are governed by the laws of Australia. Any disputes arising from your use of
              this service will be subject to the jurisdiction of the courts of Australia.
            </p>
          </div>
        </section>

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">8. Changes to these terms</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>
              We may update these terms from time to time. We will notify registered users by email when we make material changes. Continued use of the service after changes are posted constitutes acceptance of the updated terms.
            </p>
          </div>
        </section>

        <section className="border border-[var(--border)] rounded-lg bg-[var(--card)] p-6 md:p-8">
          <h2 className="text-2xl mb-4">9. Contact</h2>
          <div className="space-y-3 text-[var(--muted)] text-base leading-relaxed">
            <p>
              For questions about these terms, contact us at:
            </p>
            <p>
              <strong className="text-[var(--foreground)]">Email:</strong>{' '}
              <span className="text-[var(--accent)]">legal@pettylawsuits.com.au</span>{' '}
              <span className="text-sm">(placeholder — to be updated before launch)</span>
            </p>
            <p className="text-sm mt-2">
              Last updated: April 2026
            </p>
          </div>
        </section>

      </div>
    </main>
  )
}
